apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: '1' # 1 = 100% of traces, 0.1 = 10%
    zipkin:
      endpointAddress: 'http://localhost:9411/api/v2/spans'
  features:
    - name: resiliency
      enabled: true
  logging:
    apiLogging:
      enabled: false
